/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presionchart;

/**
 *
 * @author JoseCarlos
 */
public class Ayuda extends javax.swing.JDialog {

    /**
     * Creates new form Ayuda
     */
    public Ayuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ayuda SiMPresAr");
        setResizable(false);

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextPane4.setText("SiMPresAr 1.0.2013 \n\nEl progrma requiere un Archivo de Registros, el cul es la base de datos donde se almacenaran las mediciones realizadas a un paciente. \nSe pueden crear la cantidad de archivos de registro que se desen. Cada archivo de registro puede almacenar las mediciones de muchas personas.\nEste archivo se guarda en su computador en la direccion que usted elija.\nLos Archivos de Registros se pueden copiar, enviar y trasladar de un computador a otro sin problemas, son archivos portables, se podran interpretar siempre y cuando se cuente con el programa SiMPresAr, el cual tambien es portable.\n\nSiempre que inicie el programa su primera accion debe ser abrir el archivo, de lo contrario no se podran utilizar las funciones de analisis del sistema.\n\n-->Como crear un Archivo de Registro:\nDebe dirigirse al menu Opciones, luego al Item \"Nuevo Cinjunto de Datos\", seleccione el lugar donde guardar el archivo y colocarle un nombre al mismo. Hecho esto el sistema esta listo para recibir datos de usuario y mediciones.\n\n-->Como abrir un Archivo de Registro:\nSi ya h creado con anteriorirdad su archivo de registros, solo tendra que indicarle al sistema la ubiccion donde lo guardo, pra ello seleccione el Item\"Abrir Conjunto de Datos\" en el Menu Opciones.\n\n-->Eliminar los datos del archivo de registro:\nSi usted desea iniciar con archivo de registros vacio, puede eliminar el archivo y luego crear uno nuevo o puede selecconar el Item \"Borrar Todos los Datos\" en el menu Opciones. Con esto se reiniciara el Archivo de Registros a su estado original.\n\n ");
        jScrollPane6.setViewportView(jTextPane4);

        jTabbedPane1.addTab("Instrucciones para Archivo de Registro", jScrollPane6);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextPane1.setText("SiMPresAr 1.0.2013 \n\nIngreso de Medidas: \nPara ingresar una medición seleccione el usuario e ingrese los valores en el cuadro con el nombre \"Toma:Sistolico/Diastolico\", con dicho orden, se debe ingresar tambien la barra(/) entre las mediciones, seleccione tambien la fecha y presione el boton \"Guardar\".  \n\nVer Datos:\nEl sistema permite mostrar las ultimas 50 medidas de presion de un usuario, al iniciar en la aplicación. Despues de esto se puede seleccionar la cantidad de medidas que se desean observar en el grafico y en la tabla. Para ello seleccione la cantidad del menu desplegble \"Cantidad de Tomas\" y de click en el Boton Actualizar. las graficas se pueden copiar y utilizar en otros programas.  \n\nMenu:\nEl Menu Usuarios permite Agregar un nuevo usuario al sistema, cambiar el usuario, modificar los datos y eliminar el usuario que utiliza que usa el sistema actualmente, al hacer esto se eliminan tambien todos los registros del archivo.\n\nEditar las Mediciones:\nSi luego de introducida una medición esta esta equivocada, es posible la edicion de la misma, seleccionando el Item \"Editar/Elimnar Datos\" en el menu Opciones. A traves de este podrá cambiar la fecha y/o el valor de la medición o eliminar la misma del archivo de registros. \n\n");
        jScrollPane3.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Instrucciones de Uso", jPanel1);

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextPane2.setText("SiMPresAr 1.0.2013  \nEste programa permite llevar unregistro de las mediciones de la presion arterial de varios usuarios, de manera portable.  Genera graficas y tablas que permiten ver el historial de mediciones de una determinadopaciente. Al ingresar los datos de una medición se emplea logica borrosa para determinar en cual categoria esta la presión arterial registrada.");
        jScrollPane4.setViewportView(jTextPane2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Descripcion del Programa.", jPanel3);

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextPane3.setText("SiMPresAr 1.0.2013 \n\n¿Que es la Presión Arterial?\nLa presión arterial es la fuerza o presión que lleva la sangre a todas las partes del cuerpo. Al medir la presión arterialse conoce el resultado de la presión que ejerce la sangre contra las paredes de las arterias. El resultado de la lectura de la presión arterial se da en 2 cifras. Una de ellas es la sistólica que está arriba o sea el primer número en la lectura. La otra es llamada diastólica que está abajo y es el segundo número en la lectura.\n\n\nLa medición de la presión arterial tiene dos partes: el número de arriba (o primero) y el número de abajo (segundo). El número de arriba es la presión “sistólica” y el número de abajo, la presión “diastólica”.\n\n-->La presión sistólica es la presión arterial cuando el corazón late y bombea la sangre a través de las arterias. La presión es más alta cuando el corazón está bombeando; por eso el número sistólico siempre es más alto.\n\n-->La presión diastólica es la presión arterial entre latidos cardiacos, cuando el corazón no está bombeando. La presión arterial es más baja cuando el corazón no está bombeando; por eso el número diastólico es más bajo.\n\nLos números de su presión arterial se presentan uno arriba del otro, con la presión sistólica “arriba” de la presión diastólica.\n\n-->La presión arterial normal es menor de “120 sobre 80”, o sea 120/80. Eso significa que la presión sistólica es de 120 y la diastólica de 80.\n \n-->Una presión arterial entre 120/80 y 139/89 se llama “prehipertensión”. Esto significa que su presión arterial es más alta de lo normal y que corre el riesgo de padecer de presión arterial alta.\n\n-->Si su presión arterial es de 140/90 o más, la mayoría de las veces que se la mide, entonces usted padece de presión arterial alta.");
        jScrollPane5.setViewportView(jTextPane3);

        jTabbedPane1.addTab("Información de la Presion Arterial", jScrollPane5);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Sistema de Monitoreo<BR>&nbsp;&nbsp;de Presion Arterial</html>");
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        botonCancelar.setText("Regresar");
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Instrucciones para Archivo de Registro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ayuda dialog = new Ayuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
